apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: kafka
spec:
  containers:
  - name: kafka
    image: solsson/kafka:1.0.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
