apiVersion: v1
kind: Service
metadata:
  name: kchat-server-kconsumer
spec:
  selector:
    app: kconsumer
  ports:
  - protocol: TCP
    port: 29092 
    targetPort: 29092
    nodePort: 30292
  type: NodePort
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: kchat-server-kconsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kconsumer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kconsumer
    spec:
      containers:
      - image: hhayakaw/kchat.server.kconsumer:0.1
        name: kconsumer
        imagePullPolicy: Always
        env:
        - name: KCHAT_BOOTSTRAP_ADDRESS
          value: kafka-0.broker.kafka:9092
        ports:
        - containerPort: 29092
          name: kconsumer
